# Generated by Django 5.1 on 2024-08-15 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_attendee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='host',
        ),
    ]
